name: Build disclosures.json

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Build disclosures.json
        run: node tools/scrape-otc-and-sec.js
        env:
          SEC_USER_AGENT: "Standard Dental Labs (IR@sdl.care)"  # per SEC API guidance

      - name: Commit updated disclosures.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git status --porcelain | grep disclosures.json; then
            git add disclosures.json
            git commit -m "chore: update disclosures.json"
            git push
          else
            echo "No changes."
          fi
